# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\lgwork\py\numcode\act_do_toolbuttom.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1075, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1075, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 700))
        MainWindow.setFocusPolicy(QtCore.Qt.TabFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/JJ/.designer/backup/zq.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 0, 881, 701))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 9, 0, 9)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton_4 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_4.setMinimumSize(QtCore.QSize(0, 150))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("photo/00.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon1)
        self.toolButton_4.setIconSize(QtCore.QSize(300, 150))
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout.addWidget(self.toolButton_4, 2, 0, 1, 1)
        self.toolButton_6 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_6.setMinimumSize(QtCore.QSize(0, 150))
        self.toolButton_6.setIcon(icon1)
        self.toolButton_6.setIconSize(QtCore.QSize(300, 150))
        self.toolButton_6.setObjectName("toolButton_6")
        self.gridLayout.addWidget(self.toolButton_6, 2, 3, 1, 1)
        self.toolButton_5 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_5.setMinimumSize(QtCore.QSize(0, 150))
        self.toolButton_5.setIcon(icon1)
        self.toolButton_5.setIconSize(QtCore.QSize(300, 150))
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout.addWidget(self.toolButton_5, 2, 1, 1, 1)
        self.toolButton_10 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_10.setMinimumSize(QtCore.QSize(0, 150))
        self.toolButton_10.setIcon(icon1)
        self.toolButton_10.setIconSize(QtCore.QSize(300, 150))
        self.toolButton_10.setObjectName("toolButton_10")
        self.gridLayout.addWidget(self.toolButton_10, 5, 0, 1, 1)
        self.toolButton_11 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_11.setMinimumSize(QtCore.QSize(0, 150))
        self.toolButton_11.setIcon(icon1)
        self.toolButton_11.setIconSize(QtCore.QSize(300, 150))
        self.toolButton_11.setObjectName("toolButton_11")
        self.gridLayout.addWidget(self.toolButton_11, 5, 1, 1, 1)
        self.toolButton_12 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_12.setMinimumSize(QtCore.QSize(0, 150))
        self.toolButton_12.setIcon(icon1)
        self.toolButton_12.setIconSize(QtCore.QSize(300, 150))
        self.toolButton_12.setObjectName("toolButton_12")
        self.gridLayout.addWidget(self.toolButton_12, 5, 3, 1, 1)
        self.toolButton_9 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_9.setMinimumSize(QtCore.QSize(0, 150))
        self.toolButton_9.setIcon(icon1)
        self.toolButton_9.setIconSize(QtCore.QSize(300, 150))
        self.toolButton_9.setObjectName("toolButton_9")
        self.gridLayout.addWidget(self.toolButton_9, 4, 3, 1, 1)
        self.toolButton_7 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_7.setMinimumSize(QtCore.QSize(0, 150))
        self.toolButton_7.setIcon(icon1)
        self.toolButton_7.setIconSize(QtCore.QSize(300, 150))
        self.toolButton_7.setObjectName("toolButton_7")
        self.gridLayout.addWidget(self.toolButton_7, 4, 0, 1, 1)
        self.toolButton_8 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_8.setMinimumSize(QtCore.QSize(0, 150))
        self.toolButton_8.setIcon(icon1)
        self.toolButton_8.setIconSize(QtCore.QSize(300, 150))
        self.toolButton_8.setObjectName("toolButton_8")
        self.gridLayout.addWidget(self.toolButton_8, 4, 1, 1, 1)
        self.toolButton_1 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_1.setMinimumSize(QtCore.QSize(0, 150))
        self.toolButton_1.setIcon(icon1)
        self.toolButton_1.setIconSize(QtCore.QSize(300, 150))
        self.toolButton_1.setObjectName("toolButton_1")
        self.gridLayout.addWidget(self.toolButton_1, 1, 0, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_2.setMinimumSize(QtCore.QSize(0, 150))
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setIconSize(QtCore.QSize(300, 150))
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout.addWidget(self.toolButton_2, 1, 1, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_3.setMinimumSize(QtCore.QSize(0, 150))
        self.toolButton_3.setIcon(icon1)
        self.toolButton_3.setIconSize(QtCore.QSize(300, 150))
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout.addWidget(self.toolButton_3, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(950, 10, 101, 251))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(72)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(970, 590, 77, 83))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pb_quit = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_quit.setObjectName("pb_quit")
        self.verticalLayout.addWidget(self.pb_quit)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(930, 470, 131, 91))
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setObjectName("graphicsView")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(930, 450, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_OK = QtWidgets.QLabel(self.centralwidget)
        self.label_OK.setGeometry(QtCore.QRect(1040, 430, 31, 31))
        self.label_OK.setText("")
        self.label_OK.setObjectName("label_OK")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pb_quit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SQ——数字编码练习"))
        self.toolButton_4.setText(_translate("MainWindow", "4"))
        self.toolButton_6.setText(_translate("MainWindow", "6"))
        self.toolButton_5.setText(_translate("MainWindow", "5"))
        self.toolButton_10.setText(_translate("MainWindow", "10"))
        self.toolButton_11.setText(_translate("MainWindow", "11"))
        self.toolButton_12.setText(_translate("MainWindow", "12"))
        self.toolButton_9.setText(_translate("MainWindow", "9"))
        self.toolButton_7.setText(_translate("MainWindow", "7"))
        self.toolButton_8.setText(_translate("MainWindow", "8"))
        self.toolButton_1.setText(_translate("MainWindow", "1"))
        self.toolButton_2.setText(_translate("MainWindow", "2"))
        self.toolButton_3.setText(_translate("MainWindow", "3"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_2.setText(_translate("MainWindow", "&Next"))
        self.pushButton.setText(_translate("MainWindow", "&Analysis"))
        self.pb_quit.setText(_translate("MainWindow", "&Quit"))
        self.pb_quit.setShortcut(_translate("MainWindow", "Alt+Q"))
        self.label_13.setText(_translate("MainWindow", "结果"))

